// Date: 5/26/2014 12:46:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package arouka.btv.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnderchilla extends ModelBase
{
  //fields
    ModelRenderer Tail_1;
    ModelRenderer Tail_2;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
    ModelRenderer Snout;
  
  public ModelEnderchilla()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Tail_1 = new ModelRenderer(this, 13, 11);
      Tail_1.addBox(-1F, 0F, -1F, 2, 1, 3);
      Tail_1.setRotationPoint(0F, 19F, 1F);
      Tail_1.setTextureSize(64, 32);
      Tail_1.mirror = true;
      setRotation(Tail_1, 0.6108652F, 0F, 0F);
      Tail_2 = new ModelRenderer(this, 13, 11);
      Tail_2.addBox(-1F, 0F, 0F, 2, 1, 3);
      Tail_2.setRotationPoint(0F, 18.2F, 2.333333F);
      Tail_2.setTextureSize(64, 32);
      Tail_2.mirror = true;
      setRotation(Tail_2, 1.082104F, 0F, 0F);
      head = new ModelRenderer(this, 0, 9);
      head.addBox(-2F, -2F, -2F, 4, 4, 2);
      head.setRotationPoint(0F, 21F, -5F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 13, 0);
      body.addBox(-2F, -4F, -2F, 4, 6, 4);
      body.setRotationPoint(0F, 21F, -1F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 22);
      leg1.addBox(-1F, 0F, -2F, 2, 1, 3);
      leg1.setRotationPoint(-1F, 23F, 0F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 22);
      leg2.mirror = true;
      leg2.addBox(-1F, 0F, -2F, 2, 1, 3);
      leg2.setRotationPoint(1F, 23F, 0F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg2.mirror = false;
      leg3 = new ModelRenderer(this, 0, 16);
      leg3.addBox(-2F, -1F, -1F, 2, 2, 2);
      leg3.setRotationPoint(0F, 23F, -4F);
      leg3.setTextureSize(64, 32);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 16);
      leg4.mirror = true;
      leg4.addBox(0F, -1F, -1F, 2, 2, 2);
      leg4.setRotationPoint(0F, 23F, -4F);
      leg4.setTextureSize(64, 32);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      leg4.mirror = false;
      Ear1 = new ModelRenderer(this, 0, 4);
      Ear1.addBox(-1F, -3F, 0F, 2, 3, 1);
      Ear1.setRotationPoint(-2F, 20F, -6F);
      Ear1.setTextureSize(64, 32);
      Ear1.mirror = true;
      setRotation(Ear1, 0F, 0F, 0F);
      Ear2 = new ModelRenderer(this, 0, 4);
      Ear2.mirror = true;
      Ear2.addBox(0F, -3F, 0F, 2, 3, 1);
      Ear2.setRotationPoint(1F, 20F, -6F);
      Ear2.setTextureSize(64, 32);
      Ear2.mirror = true;
      setRotation(Ear2, 0F, 0F, 0F);
      Ear2.mirror = false;
      Snout = new ModelRenderer(this, 0, 0);
      Snout.addBox(-3F, -1F, -1F, 4, 2, 1);
      Snout.setRotationPoint(1F, 22F, -7F);
      Snout.setTextureSize(64, 32);
      Snout.mirror = true;
      setRotation(Snout, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Tail_1.render(f5);
    Tail_2.render(f5);
    head.render(f5);
    body.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    Ear1.render(f5);
    Ear2.render(f5);
    Snout.render(f5);
  }
  
  public void renderModel(float f){
	 Tail_1.render(f);
	 Tail_2.render(f);
	 head.render(f);
	 body.render(f);
	 leg1.render(f);
	 leg2.render(f);
	 leg3.render(f);
	 leg4.render(f);
	 Ear1.render(f);
	 Ear2.render(f);
	 Snout.render(f);
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
