// Date: 5/28/2014 9:06:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package arouka.btv.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelResearchStation extends ModelBase
{
  //fields
    ModelRenderer ResearchBase;
    ModelRenderer Well1;
    ModelRenderer Well2;
    ModelRenderer Well3;
    ModelRenderer Well4;
    ModelRenderer Well5;
    ModelRenderer Well6;
    ModelRenderer Well7;
    ModelRenderer Well8;
    ModelRenderer Well9;
    ModelRenderer Well10;
    ModelRenderer Well11;
    ModelRenderer Well12;
    ModelRenderer magArm1;
    ModelRenderer magArm2;
    ModelRenderer magFrame1;
    ModelRenderer magFrame2;
    ModelRenderer magFrame3;
    ModelRenderer magFrame4;
    ModelRenderer magGlass;
    ModelRenderer lazArm1;
    ModelRenderer lazArm2;
    ModelRenderer lazHead1;
    ModelRenderer lazHead2;
    ModelRenderer LazHead3;
    ModelRenderer LazHead4;
  
  public ModelResearchStation()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      ResearchBase = new ModelRenderer(this, 0, 36);
      ResearchBase.addBox(-8F, -6F, -8F, 16, 12, 16);
      ResearchBase.setRotationPoint(0F, 18F, 0F);
      ResearchBase.setTextureSize(128, 64);
      ResearchBase.mirror = true;
      setRotation(ResearchBase, 0F, 0F, 0F);
      Well1 = new ModelRenderer(this, 28, 31);
      Well1.addBox(-8F, -1.5F, -1F, 16, 3, 2);
      Well1.setRotationPoint(0F, 10.5F, -7F);
      Well1.setTextureSize(128, 64);
      Well1.mirror = true;
      setRotation(Well1, 0F, 0F, 0F);
      Well2 = new ModelRenderer(this, 28, 31);
      Well2.addBox(-8F, -1.5F, 0F, 16, 3, 2);
      Well2.setRotationPoint(0F, 10.5F, 6F);
      Well2.setTextureSize(128, 64);
      Well2.mirror = true;
      setRotation(Well2, 0F, 0F, 0F);
      Well3 = new ModelRenderer(this, 0, 21);
      Well3.addBox(-1F, -1.5F, -6F, 2, 3, 12);
      Well3.setRotationPoint(-7F, 10.5F, 0F);
      Well3.setTextureSize(128, 64);
      Well3.mirror = true;
      setRotation(Well3, 0F, 0F, 0F);
      Well4 = new ModelRenderer(this, 0, 21);
      Well4.addBox(-1F, -1.5F, -6F, 2, 3, 12);
      Well4.setRotationPoint(7F, 10.5F, 0F);
      Well4.setTextureSize(128, 64);
      Well4.mirror = true;
      setRotation(Well4, 0F, 0F, 0F);
      Well5 = new ModelRenderer(this, 28, 27);
      Well5.addBox(-6F, -1F, -1F, 12, 2, 2);
      Well5.setRotationPoint(0F, 11F, -5F);
      Well5.setTextureSize(128, 64);
      Well5.mirror = true;
      setRotation(Well5, 0F, 0F, 0F);
      Well6 = new ModelRenderer(this, 28, 27);
      Well6.addBox(-6F, -1F, -1F, 12, 2, 2);
      Well6.setRotationPoint(0F, 11F, 5F);
      Well6.setTextureSize(128, 64);
      Well6.mirror = true;
      setRotation(Well6, 0F, 0F, 0F);
      Well7 = new ModelRenderer(this, 0, 11);
      Well7.addBox(-1F, -1F, -4F, 2, 2, 8);
      Well7.setRotationPoint(-5F, 11F, 0F);
      Well7.setTextureSize(128, 64);
      Well7.mirror = true;
      setRotation(Well7, 0F, 0F, 0F);
      Well8 = new ModelRenderer(this, 0, 11);
      Well8.addBox(-1F, -1F, -4F, 2, 2, 8);
      Well8.setRotationPoint(5F, 11F, 0F);
      Well8.setTextureSize(128, 64);
      Well8.mirror = true;
      setRotation(Well8, 0F, 0F, 0F);
      Well9 = new ModelRenderer(this, 42, 18);
      Well9.addBox(-0.5F, -0.5F, -4F, 1, 1, 8);
      Well9.setRotationPoint(-3.5F, 11.5F, 0F);
      Well9.setTextureSize(128, 64);
      Well9.mirror = true;
      setRotation(Well9, 0F, 0F, 0F);
      Well10 = new ModelRenderer(this, 42, 18);
      Well10.addBox(-0.5F, -0.5F, -4F, 1, 1, 8);
      Well10.setRotationPoint(3.5F, 11.5F, 0F);
      Well10.setTextureSize(128, 64);
      Well10.mirror = true;
      setRotation(Well10, 0F, 0F, 0F);
      Well11 = new ModelRenderer(this, 28, 25);
      Well11.addBox(-3F, -0.5F, -0.5F, 6, 1, 1);
      Well11.setRotationPoint(0F, 11.5F, -3.5F);
      Well11.setTextureSize(128, 64);
      Well11.mirror = true;
      setRotation(Well11, 0F, 0F, 0F);
      Well12 = new ModelRenderer(this, 28, 25);
      Well12.addBox(-3F, -0.5F, -0.5F, 6, 1, 1);
      Well12.setRotationPoint(0F, 11.5F, 3.5F);
      Well12.setTextureSize(128, 64);
      Well12.mirror = true;
      setRotation(Well12, 0F, 0F, 0F);
      magArm1 = new ModelRenderer(this, 64, 45);
      magArm1.addBox(-4F, -1F, -8.5F, 8, 2, 17);
      magArm1.setRotationPoint(0F, 8F, 12F);
      magArm1.setTextureSize(128, 64);
      magArm1.mirror = true;
      setRotation(magArm1, 0.8922867F, 0F, 0F);
      magArm2 = new ModelRenderer(this, 64, 28);
      magArm2.addBox(-4F, -1F, -7.5F, 8, 2, 15);
      magArm2.setRotationPoint(0F, -3F, 10F);
      magArm2.setTextureSize(128, 64);
      magArm2.mirror = true;
      setRotation(magArm2, 2.50282F, 0F, 0F);
      magFrame1 = new ModelRenderer(this, 39, 3);
      magFrame1.addBox(-1F, -0.5F, -5F, 2, 1, 10);
      magFrame1.setRotationPoint(-3F, -6.5F, 1F);
      magFrame1.setTextureSize(128, 64);
      magFrame1.mirror = true;
      setRotation(magFrame1, 0F, 0F, 0F);
      magFrame2 = new ModelRenderer(this, 39, 3);
      magFrame2.addBox(-1F, -0.5F, -5F, 2, 1, 10);
      magFrame2.setRotationPoint(3F, -6.5F, 1F);
      magFrame2.setTextureSize(128, 64);
      magFrame2.mirror = true;
      setRotation(magFrame2, 0F, 0F, 0F);
      magFrame3 = new ModelRenderer(this, 29, 22);
      magFrame3.addBox(-2F, -0.5F, -1F, 4, 1, 2);
      magFrame3.setRotationPoint(0F, -6.5F, -3F);
      magFrame3.setTextureSize(128, 64);
      magFrame3.mirror = true;
      setRotation(magFrame3, 0F, 0F, 0F);
      magFrame4 = new ModelRenderer(this, 29, 22);
      magFrame4.addBox(-2F, -0.5F, -1F, 4, 1, 2);
      magFrame4.setRotationPoint(0F, -6.5F, 4F);
      magFrame4.setTextureSize(128, 64);
      magFrame4.mirror = true;
      setRotation(magFrame4, 0F, 0F, 0F);
      magGlass = new ModelRenderer(this, 0, 0);
      magGlass.addBox(-2F, 0F, -2.5F, 4, 0, 5);
      magGlass.setRotationPoint(0F, -6F, 0.5F);
      magGlass.setTextureSize(128, 64);
      magGlass.mirror = true;
      setRotation(magGlass, 0F, 0F, 0F);
      lazArm1 = new ModelRenderer(this, 64, 15);
      lazArm1.addBox(0F, 0F, 0F, 4, 1, 12);
      lazArm1.setRotationPoint(-15F, 7F, -10F);
      lazArm1.setTextureSize(128, 64);
      lazArm1.mirror = true;
      setRotation(lazArm1, -0.6283185F, 0.8870379F, 0F);
      lazArm2 = new ModelRenderer(this, 64, 15);
      lazArm2.addBox(0F, 0F, 0F, 4, 1, 12);
      lazArm2.setRotationPoint(-9F, -1F, -5.5F);
      lazArm2.setTextureSize(128, 64);
      lazArm2.mirror = true;
      setRotation(lazArm2, -2.254555F, 0.9239978F, 0F);
      lazHead1 = new ModelRenderer(this, 22, 14);
      lazHead1.addBox(0F, 0F, 0F, 4, 1, 6);
      lazHead1.setRotationPoint(-5F, -2F, -2.4F);
      lazHead1.setTextureSize(128, 64);
      lazHead1.mirror = true;
      setRotation(lazHead1, -2.842834F, 0.9239978F, 0F);
      lazHead2 = new ModelRenderer(this, 24, 9);
      lazHead2.addBox(0F, 0F, 0F, 3, 1, 4);
      lazHead2.setRotationPoint(-5F, -1F, -3F);
      lazHead2.setTextureSize(128, 64);
      lazHead2.mirror = true;
      setRotation(lazHead2, -2.842834F, 0.9239978F, 0F);
      LazHead3 = new ModelRenderer(this, 24, 5);
      LazHead3.addBox(0F, 0F, 0F, 2, 1, 3);
      LazHead3.setRotationPoint(-4.9F, 0F, -3.6F);
      LazHead3.setTextureSize(128, 64);
      LazHead3.mirror = true;
      setRotation(LazHead3, -2.842834F, 0.9239978F, 0F);
      LazHead4 = new ModelRenderer(this, 24, 1);
      LazHead4.addBox(0F, 0F, 0F, 1, 3, 1);
      LazHead4.setRotationPoint(-4.7F, 3F, -4F);
      LazHead4.setTextureSize(128, 64);
      LazHead4.mirror = true;
      setRotation(LazHead4, -2.842834F, 0.9239978F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    ResearchBase.render(f5);
    Well1.render(f5);
    Well2.render(f5);
    Well3.render(f5);
    Well4.render(f5);
    Well5.render(f5);
    Well6.render(f5);
    Well7.render(f5);
    Well8.render(f5);
    Well9.render(f5);
    Well10.render(f5);
    Well11.render(f5);
    Well12.render(f5);
    magArm1.render(f5);
    magArm2.render(f5);
    magFrame1.render(f5);
    magFrame2.render(f5);
    magFrame3.render(f5);
    magFrame4.render(f5);
    magGlass.render(f5);
    lazArm1.render(f5);
    lazArm2.render(f5);
    lazHead1.render(f5);
    lazHead2.render(f5);
    LazHead3.render(f5);
    LazHead4.render(f5);
  }
  
  public void renderModel(float f){
	    ResearchBase.render(f);
	    Well1.render(f);
	    Well2.render(f);
	    Well3.render(f);
	    Well4.render(f);
	    Well5.render(f);
	    Well6.render(f);
	    Well7.render(f);
	    Well8.render(f);
	    Well9.render(f);
	    Well10.render(f);
	    Well11.render(f);
	    Well12.render(f);
	    magArm1.render(f);
	    magArm2.render(f);
	    magFrame1.render(f);
	    magFrame2.render(f);
	    magFrame3.render(f);
	    magFrame4.render(f);
	    magGlass.render(f);
	    lazArm1.render(f);
	    lazArm2.render(f);
	    lazHead1.render(f);
	    lazHead2.render(f);
	    LazHead3.render(f);
	    LazHead4.render(f);  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
