// Date: 5/28/2014 9:09:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package arouka.btv.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBookStand extends ModelBase
{
  //fields
    ModelRenderer baseWood;
    ModelRenderer baseGold;
    ModelRenderer beamWood;
    ModelRenderer plat1;
    ModelRenderer plat2;
    ModelRenderer plat3;
    ModelRenderer plat4;
    ModelRenderer plat5;
    ModelRenderer plat6;
    ModelRenderer plat7;
    ModelRenderer plat8;
    ModelRenderer plat9;
    ModelRenderer plat10;
  
  public ModelBookStand()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      baseWood = new ModelRenderer(this, 0, 49);
      baseWood.addBox(-7F, -0.5F, -7F, 14, 1, 14);
      baseWood.setRotationPoint(0F, 23.5F, 0F);
      baseWood.setTextureSize(64, 64);
      baseWood.mirror = true;
      setRotation(baseWood, 0F, 0F, 0F);
      baseGold = new ModelRenderer(this, 24, 17);
      baseGold.addBox(-5F, -0.5F, -5F, 10, 1, 10);
      baseGold.setRotationPoint(0F, 23F, 0F);
      baseGold.setTextureSize(64, 64);
      baseGold.mirror = true;
      setRotation(baseGold, 0F, 0F, 0F);
      beamWood = new ModelRenderer(this, 0, 26);
      beamWood.addBox(-4F, -7.5F, -4F, 8, 15, 8);
      beamWood.setRotationPoint(0F, 15F, 0F);
      beamWood.setTextureSize(64, 64);
      beamWood.mirror = true;
      setRotation(beamWood, 0F, 0F, 0F);
      plat1 = new ModelRenderer(this, 0, 0);
      plat1.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat1.setRotationPoint(0F, 6.9F, 0F);
      plat1.setTextureSize(64, 64);
      plat1.mirror = true;
      setRotation(plat1, 0.0349066F, 0F, 0F);
      plat2 = new ModelRenderer(this, 0, 0);
      plat2.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat2.setRotationPoint(0F, 6.8F, 0F);
      plat2.setTextureSize(64, 64);
      plat2.mirror = true;
      setRotation(plat2, 0.0698132F, 0F, 0F);
      plat3 = new ModelRenderer(this, 0, 0);
      plat3.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat3.setRotationPoint(0F, 6.7F, 0F);
      plat3.setTextureSize(64, 64);
      plat3.mirror = true;
      setRotation(plat3, 0.1047198F, 0F, 0F);
      plat4 = new ModelRenderer(this, 0, 0);
      plat4.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat4.setRotationPoint(0F, 6.6F, 0F);
      plat4.setTextureSize(64, 64);
      plat4.mirror = true;
      setRotation(plat4, 0.1396263F, 0F, 0F);
      plat5 = new ModelRenderer(this, 0, 0);
      plat5.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat5.setRotationPoint(0F, 6.5F, 0F);
      plat5.setTextureSize(64, 64);
      plat5.mirror = true;
      setRotation(plat5, 0.1745329F, 0F, 0F);
      plat6 = new ModelRenderer(this, 0, 0);
      plat6.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat6.setRotationPoint(0F, 6.4F, 0F);
      plat6.setTextureSize(64, 64);
      plat6.mirror = true;
      setRotation(plat6, 0.2094395F, 0F, 0F);
      plat7 = new ModelRenderer(this, 0, 0);
      plat7.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat7.setRotationPoint(0F, 6.3F, 0F);
      plat7.setTextureSize(64, 64);
      plat7.mirror = true;
      setRotation(plat7, 0.2443461F, 0F, 0F);
      plat8 = new ModelRenderer(this, 0, 0);
      plat8.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat8.setRotationPoint(0F, 6.2F, 0F);
      plat8.setTextureSize(64, 64);
      plat8.mirror = true;
      setRotation(plat8, 0.2792527F, 0F, 0F);
      plat9 = new ModelRenderer(this, 0, 0);
      plat9.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat9.setRotationPoint(0F, 6.1F, 0F);
      plat9.setTextureSize(64, 64);
      plat9.mirror = true;
      setRotation(plat9, 0.3141593F, 0F, 0F);
      plat10 = new ModelRenderer(this, 0, 0);
      plat10.addBox(-8F, -0.5F, -8F, 16, 1, 16);
      plat10.setRotationPoint(0F, 6F, 0F);
      plat10.setTextureSize(64, 64);
      plat10.mirror = true;
      setRotation(plat10, 0.3490659F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    baseWood.render(f5);
    baseGold.render(f5);
    beamWood.render(f5);
    plat1.render(f5);
    plat2.render(f5);
    plat3.render(f5);
    plat4.render(f5);
    plat5.render(f5);
    plat6.render(f5);
    plat7.render(f5);
    plat8.render(f5);
    plat9.render(f5);
    plat10.render(f5);
  }
  
  public void renderModel(float f){
	  	baseWood.render(f);
	    baseGold.render(f);
	    beamWood.render(f);
	    plat1.render(f);
	    plat2.render(f);
	    plat3.render(f);
	    plat4.render(f);
	    plat5.render(f);
	    plat6.render(f);
	    plat7.render(f);
	    plat8.render(f);
	    plat9.render(f);
	    plat10.render(f);
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
